// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcX6aGqjuUXrdMOMW3LGosOZWaLOduzi4',
    appId: '1:653780980595:web:70a1f18f80ad836aff6b06',
    messagingSenderId: '653780980595',
    projectId: 'whatsapp-messenger-677bd',
    authDomain: 'whatsapp-messenger-677bd.firebaseapp.com',
    storageBucket: 'whatsapp-messenger-677bd.appspot.com',
    measurementId: 'G-EM64Q81R63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClvlfNf5AJhAcx2uGlWgCVuBcsRzSqb4I',
    appId: '1:653780980595:android:02ecc9b343ae8e39ff6b06',
    messagingSenderId: '653780980595',
    projectId: 'whatsapp-messenger-677bd',
    storageBucket: 'whatsapp-messenger-677bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMjv4fM5zTq2gywPc_67Go8W-R3rYhzIQ',
    appId: '1:653780980595:ios:ef9d7c300907b8beff6b06',
    messagingSenderId: '653780980595',
    projectId: 'whatsapp-messenger-677bd',
    storageBucket: 'whatsapp-messenger-677bd.appspot.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );
}
